on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  goaction:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Update action files
      uses: posener/goaction@v1.1.0
      with:
        name: goaction-issues-example
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'